### Importing libraries

In [180]:
pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\Talha\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\Talha\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### READING THE DATA

In [10]:
df=pd.read_csv('Student_performance_data _.csv')
df

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,1,0,3,10.680555,2,0,4,1,0,0,0,3.455509,0.0
2388,3389,17,0,0,1,7.583217,4,1,4,0,1,0,0,3.279150,4.0
2389,3390,16,1,0,2,6.805500,20,0,2,0,0,0,1,1.142333,2.0
2390,3391,16,1,1,0,12.416653,17,0,2,0,1,1,0,1.803297,1.0
2391,3392,16,1,0,2,17.819907,13,0,2,0,0,0,1,2.140014,1.0

In [11]:
df.sample(9)

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
1803,2804,18,1,0,0,6.656367,12,0,4,0,0,0,0,2.499681,3.0
471,1472,18,0,1,2,4.003084,22,0,2,1,1,0,0,1.361933,4.0
2064,3065,17,0,1,2,6.694707,13,0,3,0,0,0,0,1.829811,4.0
2304,3305,15,0,1,1,2.244821,8,0,4,1,0,0,0,2.139864,3.0
1470,2471,15,0,0,2,8.802415,1,1,1,1,0,1,0,3.307378,1.0
1907,2908,15,1,1,1,15.098804,23,0,2,0,0,0,1,0.827339,4.0
1237,2238,18,1,1,3,9.043659,23,0,4,1,1,0,0,1.362234,4.0
973,1974,17,1,1,2,5.045057,14,1,1,1,0,0,0,1.735957,4.0
1908,2909,16,1,0,2,6.587070,27,1,3,1,0,0,1,0.875884,4.0

Viewing the element will be using to predict

In [12]:
x=df[['GPA','Absences','Tutoring','StudyTimeWeekly']]
y=df['GradeClass']

In [13]:
x

           GPA  Absences  Tutoring  StudyTimeWeekly
0     2.929196         7         1        19.833723
1     3.042915         0         0        15.408756
2     0.112602        26         0         4.210570
3     2.054218        14         0        10.028829
4     1.288061        17         1         4.672495
...        ...       ...       ...              ...
2387  3.455509         2         0        10.680555
2388  3.279150         4         1         7.583217
2389  1.142333        20         0         6.805500
2390  1.803297        17         0        12.416653
2391  2.140014        13         0        17.819907

[2392 rows x 4 columns]

In [14]:
x.info()

<class 'pandas.DataFrame'>
RangeIndex: 2392 entries, 0 to 2391
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   GPA              2392 non-null   float64
 1   Absences         2392 non-null   int64
 2   Tutoring         2392 non-null   int64
 3   StudyTimeWeekly  2392 non-null   float64
dtypes: float64(2), int64(2)
memory usage: 74.9 KB

In [15]:
y

0       2.0
1       1.0
2       4.0
3       3.0
4       4.0
       ...
2387    0.0
2388    4.0
2389    2.0
2390    1.0
2391    1.0
Name: GradeClass, Length: 2392, dtype: float64

In [16]:
y.info()

<class 'pandas.Series'>
RangeIndex: 2392 entries, 0 to 2391
Series name: GradeClass
Non-Null Count  Dtype
--------------  -----
2392 non-null   float64
dtypes: float64(1)
memory usage: 18.8 KB

### TRAINING AND BUILDING THE MODEL

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.12,random_state=42)

In [19]:
model=LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)
predict=model.predict(x_test)
score=accuracy_score(y_test,predict)
print(score)

0.8333333333333334

In [21]:
test_students = pd.DataFrame([
    [3.9, 1, 1,17],
    [1.8, 15, 0,8],
    [2.7, 5, 0,3]
], columns=['GPA', 'Absences', 'Tutoring','StudyTimeWeekly'])

predictions = model.predict(test_students)

probabilities = model.predict_proba(test_students)

for i, student in enumerate(['Student A', 'Student B', 'Student C']):
    print(f"{student}")
    print(f"Predicted Grade: {predictions[i]}")
    print(f"Probability of Passing (Class 1): {probabilities[i][1] * 100}%")
    print(f"Probability of Passing (Class 2): {probabilities[i][2] * 100}%")
    print(f"Probability of Passing (Class 3): {probabilities[i][3] * 100}%\n")

Student A
Predicted Grade: 1.0
Probability of Passing (Class 1): 54.820543152986865%
Probability of Passing (Class 2): 12.421695885895295%
Probability of Passing (Class 3): 1.0716948643996613%

Student B
Predicted Grade: 4.0
Probability of Passing (Class 1): 1.215855044112914%
Probability of Passing (Class 2): 8.255117610740479%
Probability of Passing (Class 3): 27.648508782947207%

Student C
Predicted Grade: 2.0
Probability of Passing (Class 1): 20.25771325146547%
Probability of Passing (Class 2): 42.78973070993208%
Probability of Passing (Class 3): 28.749296634776517%

### ASKED THIS FROM GOOGLE

In [22]:
from sklearn.metrics import classification_report

print(classification_report(y_test, model.predict(x_test)))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        14
         1.0       0.58      0.70      0.63        27
         2.0       0.76      0.87      0.81        45
         3.0       0.86      0.63      0.73        49
         4.0       0.90      0.99      0.94       153

    accuracy                           0.83       288
   macro avg       0.62      0.64      0.62       288
weighted avg       0.80      0.83      0.81       288

C:\Users\Talha\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Talha\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Talha\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])